[package]
name = "perf"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
publish = false

[[bin]]
name = "quinn-perf"
path = "src/bin/perf.rs"

[features]
# NOTE: Please keep this in sync with the feature list in `.github/workflows/codecov.yml`, see
# comment in that file for more information.
default = ["json-output", "qlog"]
# Allow for json output from the perf client
json-output = ["serde", "serde_json"]
# Enable qlog support
qlog = ["quinn-smol/qlog"]

[dependencies]
anyhow = { workspace = true }
async-io = { workspace = true }
async-lock = { workspace = true }
async-signal = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
hdrhistogram = { workspace = true }
quinn-smol = { path = "../quinn" }
quinn-proto-smol = { path = "../quinn-proto" }
rcgen = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true, optional = true  }
serde_json = { workspace = true, optional = true }
smol = { workspace = true }
smol-macros = { workspace = true }
socket2 = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[lints]
workspace = true
