[package]
name = "bench"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
publish = false

[dependencies]
anyhow = { workspace = true }
async-lock = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
hdrhistogram = { workspace = true }
quinn-smol = { path = "../quinn", features = ["ring"] }
rcgen = { workspace = true }
rustls = { workspace = true }
smol = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[lints]
workspace = true
